### ISSUE TITLE
Cannot run video displayless

### ISSUE THREAD

**Issue by BenChung** [videolang/video#1]
When connecting via SSH to a computer with no attached monitor (running Debian Stretch), the following error occurred when trying `raco video`:

`
Unable to init server: Could not connect: Connection refused
Gtk initialization failed for display ":0"
  context...:
   /usr/racket/share/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt: [running body]
   /usr/racket/share/pkgs/gui-lib/mred/private/wx/gtk/init.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/private/wx/gtk/platform.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/private/wx/platform.rkt: [running body]
   /usr/racket/share/pkgs/gui-lib/mred/private/kernel.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/private/mred.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/mred.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/main.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/racket/gui/base.rkt: [traversing imports]
   /home/benchung/.racket/6.9/pkgs/video/video/player.rkt: [traversing imports]
   /home/benchung/.racket/6.9/pkgs/video/video/raco.rkt: [traversing imports]
   (submod /home/benchung/.racket/6.9/pkgs/video/video/raco.rkt main): [traversing imports]
   /usr/racket/collects/raco/raco.rkt: [running body]
   /usr/racket/collects/raco/main.rkt: [running body]
`

**Comment by LeifAndersen** [comment]
So, for anyone running into this issue by googling it, the easy solution is to use `xvfb`, if you run the command as:

```
xvfb-run raco video <blah>
```

Then you can run video in headless mode. This is indicative of a much larger problem, namely, that video should only try to spin up a GUI when you are trying to preview a video, as it doesn't need one for just rendering.

**Comment by LeifAndersen** [comment]
Alright, I'm really excited about this, v0.2 no longer requires X to run.
