### ISSUE TITLE
Specify output details from within video description file

### ISSUE THREAD

**Issue by BenChung** [videolang/video#14]
Right now, if you want to specify a output resolution and frame rate, for example, that has to be done either in an explicit call to render or from the raco video command line. However, this has the unfortunate property of causing a potentially important property of the video (that can have impacts on arrangement, among others) to be specified purely in the command line, rather than in the video description script. It would be nice to have a way to declare the renderer properties from within the video script.

**Comment by LeifAndersen** [comment]
This is actually currently possible, except for the output file. Is that an important thing?

```
#lang video
#:properties (hash "width" 1920
                   "height" 1080
                   "start" 0
                   "end" 60)

(color "green")
```

**Comment by LeifAndersen** [comment]
I am going to close this because I think the solution I suggested is what you are referring to. Please feel free to re-open it if I'm wrong about that.

Thank you again for submitting a bug. :)
