### ISSUE TITLE
Clip length in seconds

### ISSUE THREAD

**Issue by BenChung** [videolang/video#15]
Right now, clip length is specified in terms of number of frames, which is less than ideal, as the output frames per second can change depending on command line flags, among other things. It would be better if clip length could be specified in terms of seconds, instead of frames, allowing the video description to be made independent of output FPS.

**Comment by LeifAndersen** [comment]
As with the other issues, v0.2 now specifies video length in seconds. So I'm going to close this. Again, thanks.
