### ISSUE TITLE
get-property types

### ISSUE THREAD

**Issue by BenChung** [videolang/video#17]
The type returned by get-property and the mechanism to set it has an unfortunate wart, in that the type is specified by a symbol passed as the third argument, an undocumented behavior. It would be nice if get-property could automatically detect what the type of the result was, or, barring that, document the symbols.

**Comment by LeifAndersen** [comment]
I agree. Ditching libmlt will fix this, and that should happen in a week or so.

**Comment by LeifAndersen** [comment]
This has been dropped as of v0.2. Thanks again.
