### ISSUE TITLE
Showing progress bar for renderer is difficult

### ISSUE THREAD

**Issue by BenChung** [videolang/video#18]
As noted in the documentation, it's possible to display a progress bar for the current state of the renderer. However, the documented way to do this is quite complex, despite the desire for a progress bar being presumably fairly universal. It would be nice if there was a mechanism to show a progress bar that was more accessible, rather than having to use explicit threading.

**Comment by LeifAndersen** [comment]
v0.2 Adds a render/pretty function which is much cleaner. Thanks again for reporting this.
