### ISSUE TITLE
Extracting separate streams as clips requires use of video/core functionality

### ISSUE THREAD

**Issue by BenChung** [videolang/video#2]
I'm working on editing the video for a conference, and the separate video sources are encoded in a single container, as separate streams. In order to extract these streams in #lang video (thanks to @LeifAndersen), I need to use video/core functionality, as follows:

`(require video/core)
(define screen
  (make-producer #:type `avformat
                             #:source "test.mov"
                             #:prop (hash "video-index" 0)))`

This works, but is a bit ungainly. Ideally, there should be some way to do this that doesn't require the use of primitives.

**Comment by LeifAndersen** [comment]
Commit b6660ed fixes this.

Thanks again for reporting.
