### ISSUE TITLE
Solid colors and composite-transition don't get along well

### ISSUE THREAD

**Issue by BenChung** [videolang/video#22]
When a color is used as the first input to a composite-transition, the transition will try to fetch the size of the color, which is undefined in the trivial case, causing a crash when it attempts to call get-property. This error is demonstrated by the following code:

``` 
#lang racket
(require video/base)
(require video/render)
(define green (color "green"))
(define red (color "red"))

(define breaks
  (multitrack
   green
   (composite-transition 0 0 1/2 1/2)
   red))
(render breaks "color.mov"
               #:width 1280
               #:height 720
               #:start 0
               #:end 2
               #:fps 24)
```

**Comment by LeifAndersen** [comment]
Commit#: 7cd45041cb92b12ab2e4b077ed7ab0e6e0696d73 fixes this.
