### ISSUE TITLE
Video fails to build due to ffmpeg version error on some systems

### ISSUE THREAD

**Issue by takikawa** [videolang/video#25]
Here's the error message: `FFmpeg libavutil version 55.34.101 incompatible with Video`

This happens on Debian stable which presumably uses an older version of ffmpeg. It would be nice if video could work on older versions too.

**Comment by LeifAndersen** [comment]
This is correct. At the moment Video only works with FFmpeg 3.3+. There are a few avbuffersink calls Video currently uses which are only in 3.3. However, they would be fairly easy to remove if you are interested. The file that you would need to modify is: `video/private/ffmpeg-pipeline.rkt`

Thank you for reporting this.

**Comment by LeifAndersen** [comment]
Commit ae66f4def70e6415b7c2f055f0863ac39f52c6a7 fixes this. Thanks.
