### ISSUE TITLE
Documentation for composite-transition is rather lacking

### ISSUE THREAD

**Issue by BenChung** [videolang/video#3]
The documentation for composite-transition, right now, consists of

```
(composite-transition	 [	#:length length	 
 	 	#:top top	 
 	 	#:bottom bottom])	 
 → (or/c transition? field-element?)
  length : (or/c nonnegative-integer? #f) = #f
  top : (or/c any/c #f) = #f
  bottom : (or/c any/c #f) = #f
```

However, pulling an example, we see

```
(composite-transition 0 0 1/2 1)
```

The former does not explain the latter in pretty much any way - what are the numbers, for example? What units are they in? Improving this would be a major boon to understanding.

**Comment by LeifAndersen** [comment]
Thanks for the heads up. Commit d6f068df2fd919a84347e242c750d24899fdcba3 fixes this.
