### ISSUE TITLE
wishlist: pict as producer

### ISSUE THREAD

**Issue by takikawa** [videolang/video#32]
One thing I thought the API might include was a function that goes from a `pict` (or perhaps a function producing `pict`s given a frame number, say) to a producer. Maybe I missed it in the docs, but it seems like it'd be a neat wishlist item.

**Comment by LeifAndersen** [comment]
Yes it would be, and it was a design goal, although not quite there yet. Although I'm absolutely happy to make it. Any suggestions on what API you would like?

Either it could go from a sequence of picts to a producer and a single pict to a producer, or have a thunk that produces a sequence of picts to a producer. Currently I'm inclined to do the former, but either way is fine with me.

**Comment by LeifAndersen** [comment]
07e04b263698e5b90e611e1e39a3881c25a90a10 adds this.

Thanks for the suggestion.
