### ISSUE TITLE
`image` not defined (and conversion error)

### ISSUE THREAD

**Issue by jmct** [videolang/video#42]
Hey Leif,

I'm looking to use `video` for the ICFP videos and I'm running in to some issues. I'm happy to help solve these issues, I'm just a racket newbie and will need some guidance.

Setup: Arch Linux, video installed with `raco pkg install video-testing`.

With a file with the following contents:

```{racket}
#lang video ; icfp.vid

(image "logo/ICFP2017logo_final.png" #:length 200)

(clip "../scheme/apm.mp4")
```
I get the following contract violation:

```
image: unbound identifier in module
  in: image
  context...:
   /home/jmct/.racket/6.11/pkgs/video-testing/video/private/camera-icon.rkt:60:3
   /usr/share/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /usr/share/racket/collects/ffi/unsafe/atomic.rkt:72:13
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:785:4: dispatch-on-event method in window%
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

Now, after diffing around a bit I found an example of yours that used images, but it seemed to use the desugared version, seeing if that would fix it I changed the line with `image` to:

```{racket}
(clip "logo/ICFP2017logo_final.png" #:properties (hash "length" 200))
```
It does seem to get a bit further, as now I get the following error:

```
graph-config: -22 : EINVAL
  context...:
   /home/jmct/.racket/6.11/pkgs/video-testing/video/private/ffmpeg-pipeline.rkt:1175:0: init-filter-graph
   /home/jmct/.racket/6.11/pkgs/video-testing/video/render.rkt:293:7
   /home/jmct/.racket/6.11/pkgs/video-testing/video/player.rkt:73:4: play method in video-player-server%
   /home/jmct/.racket/6.11/pkgs/video-testing/video/player.rkt:362:0: preview4
   /usr/share/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /usr/share/racket/collects/ffi/unsafe/atomic.rkt:72:13
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:785:4: dispatch-on-event method in window%
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```
If I only have the second line (that directly imports the `.mp4` it works fine (though there is a squeal (sound) at the beginning that doesn't happen when I play it through FFplay, but that's super minor).

I have access to a mac machine at work, so I will try that tomorrow and report back. It could very well be an issue with Arch Linux compatibility.

Thanks for any help!

**Comment by LeifAndersen** [comment]
Yes. The `image` function was removed in the testing branch as its functionality was replaced with `clip`.

If you have a unix machine it might make sense to use the stable version of video. (If MLT is in the arch repo, it is in the osx ones.) While the design isn't quite as nice, it is a little more tested.

Either way though, this sounds like a bug so I will fix it, thanks. :)

**Comment by LeifAndersen** [comment]
Has there been any progress on these videos?

I have also done some work on cleaning up error messages to help make debugging easier.

**Comment by LeifAndersen** [comment]
I'm going to close this issue, as its over a year old with no updates. Video has become significantly more stable in that time. So feel free to re-open it if the issue persists. :)
