### ISSUE TITLE
Overlaying images/text onto videos

### ISSUE THREAD

**Issue by srfoster** [videolang/video#59]
![screen shot 2018-10-04 at 9 15 09 am](https://user-images.githubusercontent.com/764563/46487911-1419a380-c7b6-11e8-8b1a-b0af0b2a3a25.png)

I was trying out the overlaying of transparent picts onto videos.  Am I doing it right, though?  A few things are happening that are puzzling: Video is grayscale?  Background doesn't seem to be transparent?  Video seems to be subdivided into 3 parts?

The same happens when I run `examples/7-watermark.rkt`

Thanks for all the hard work on this lang.  :)

**Comment by LeifAndersen** [comment]
Hmm...your code looks right. I suspect the three parts are because Video separated out the three color channels (RGB) into separate feeds. Probably a simple bug on my end.

**Comment by LeifAndersen** [comment]
Ah, okay, its a bug in `composite-merge`. An immediate fix is to use `overlay-merge` instead:

```
(multitrack
 (clip the-clip)
 (overlay-merge 0 0 100 100)
 (p:colorize (p:text "HELLO" "Helvetica" 1024) "white"))
```

**Comment by LeifAndersen** [comment]
(Also worth noting, while it doesn't preview correctly, it does seem to _render_ correctly.)

**Comment by LeifAndersen** [comment]
And finally, ce7fd88f7d34c5ebe17cb0faecb05795df5e32e9 fixes this. Thanks for reporting.

**Comment by srfoster** [comment]
Thanks for fixing!
