### ISSUE TITLE
Dependency not found.

### ISSUE THREAD

**Issue by Antigen-1** [videolang/video#68]
https://github.com/videolang/video/blob/aa958b5ab250c8a202b24444935255d773608ea6/info.rkt#LL43C28-L43C28

**Comment by LeifAndersen** [comment]
Is this on an m1 mac?

**Comment by Antigen-1** [comment]
Actually, it's on ubuntu22.04.

**Comment by Antigen-1** [comment]
I can't find a `libvid-x86_64-linux` package in the [catalog](https://pkgs.racket-lang.org)

**Comment by LeifAndersen** [comment]
Hmm...I see. It seems like the catalog dropped it for some reason...strange. I'll re-add it tomorrow morning.

**Comment by Antigen-1** [comment]
Thanks a lot

**Comment by Antigen-1** [comment]
Hmm...There seems to be a `libvid-x86_64-linux-linux` package in the catalog now. Is this a typo?

**Comment by LeifAndersen** [comment]
It seems to be there now.  It looks like I am able to download install video now.

**Comment by Antigen-1** [comment]
That's wonderful! Thank you very much.
